Using rune function to convert from string to int
Error: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)